# print ("Try the following mathmatical calculations and guess what is happening?")
print (("Dar Soorate Estefade az / khahim dasht : Taghsime sahihe 2 adad"))
print ("Mesal : 3/2=",3/2)
print (("Dar Soorate Estefade az // khahim dasht : taghsime bedune ashar 2 adad"))
print ("Mesal : 3//2=",3//2)
print (("Dar Soorate Estefade az % khahim dasht : baghimande taghsime 2 adad"))
print ("Mesal : 3%2=",3%2)
print (("Dar Soorate Estefade az ** khahim dasht : adade aval be tavane adade dovom"))
print ("Mesal : 3**2=",3**2)
