name=input('lotfan name khod ra vared konid  :' )
family=input('lotfan family khod ra vared konid  :' )
age=int(input('lotfan sen khod ra vared konid  :' ))
avg=float(input('lotfan moadel tahsili khod ra vared konid  :' ))
print(list(('name:',name  ,'family:',family  ,'sen:',age  ,'moadel:',avg)))